### ISSUE TITLE
luo.lua:1297: bad argument #7 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by PizzaCrust** [oeed/Luo#1]
C:\Lua\bin\lua51.exe: luo.lua:1297: bad argument #7 to 'format' (string expected, got nil)
stack traceback:
        [C]: in function 'format'
        luo.lua:1297: in function 'add'
        luo.lua:2326: in main chunk
        [C]: ?
Starting parse...
Parsed 'test.luo' without error in 0s!
Parsed in 0s!
Starting compile...
Compiling: UnefficentExample

**Comment by oeed** [comment]
Can you please elaborate a bit as to how you caused this?

**Comment by PizzaCrust** [comment]
Luo file:

``` lua
class Meow 
end
```

'lua51 luo.lua test.luo'

**Comment by oeed** [comment]
I'm completely ditching the old code, so this doesn't really matter anymore. Thanks though!
