### ISSUE TITLE
Nil reference on line 2367

### ISSUE THREAD

**Issue by dmarcuse** [oeed/Luo#2]
`lua: luo:2367: attempt to index global 'blocks' (a nil value)`

Pretty straightforward error, tested in CC 1.79 and Lua 5.1.

**Comment by oeed** [comment]
I'm completely ditching the old code, so this doesn't really matter anymore. Thanks though!

**Comment by dmarcuse** [comment]
No problem, I'll be keeping an eye on this project 😛
